$rofiCache = $HOME/.cache/theme

env = ROFI_THMB_W,url("$rofiCache/wall.thmb", width)
env = ROFI_THMB_H,url("$rofiCache/wall.thmb", height)
env = ROFI_BLUR_W,url("$rofiCache/wall.blur", width)
env = ROFI_BLUR_H,url("$rofiCache/wall.blur", height)
env = ROFI_SQRE_H,url("$rofiCache/wall.sqre", height)
env = ROFI_QUAD_W,url("$rofiCache/wall.quad", width)
