wsl = false
no-multigrid = false
vsync = true
maximized = false
tabs = false
srgb = false
idle = true
frame = "none"

[font]
normal = { family = "DM Mono Nerd Font", style = "Regular" }
italic = { family = "DM Mono Nerd Font", style = "Regular Italic" }
bold = { family = "DM Mono Nerd Font", style = "Medium" }

size = 12
edging = "subpixelantialias"
hinting = "full"

[box-drawing.sizes]
default = [1, 2]  # Thin and thick values respectively, for all sizes

[font.features]
"DMMono Nerd Font" = [
  "+ss07",
  "+ss09",
  "+cv25",
  "+cv26",
  "+cv27",
  "+cv28",
  "+cv29",
  "+cv30",
  "+cv31",
  "+cv32",
]
