monitor = , preferred, auto, 1

# Disable logind handle-lid-switch to manage it manually /etc/systemd/logind.conf
# HandleLidSwitch=ignore
# HandleLidSwitchExternalPower=ignore
# HandleLidSwitchDocked=ignore

bindl = , switch:on:Lid Switch, exec, lid-monitor-handler close
bindl = , switch:off:Lid Switch, exec, lid-monitor-handler open

exec = setup-monitors
